name: DevSecOps Pipeline

# 언제 이 파이프라인을 실행할 것인가? (main 브랜치에 코드가 Push 될 때마다)
on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest # 깃허브가 빌려주는 무료 리눅스 서버

    steps:
    # 1. 깃허브 서버로 내 코드를 다운받아오는 기본 액션
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. 파이썬 환경 세팅
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # ==========================================
    #  [미션]: 아래에 3번과 4번 스텝을 직접 작성해 보세요!
    # ==========================================
    
    # 3. Bandit 패키지를 설치하는 스텝을 작성하세요. (hint: run: pip install ...)
    - name: Install Bandit
      run: pip install bandit
      
    # 4. Bandit을 실행하여 현재 폴더(.)의 모든 코드를 검사하는 스텝을 작성하세요.
    - name: Run Security Scan
      run: bandit -r .
    
    # 5. 도커 이미지 빌드
    - name: Build Docker Image
      run: docker build -t my-secure-app:latest .

    # 6. Trivy 깃허브 마켓플레이스 액션 이용 (보안 게이트 강화)
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-secure-app:latest
        format: table                   # 결과를 터미널에 표 형태로 예쁘게 출력
        exit-code: 1                   # (핵심) 취약점이 발견되면 1을 반환하여 파이프라인 실패 처리
        ignore-unfixed: true            # 아직 패치되지 않은 취약점은 무시 (선택 사항)
        vuln-type: library           # 라이브러리 취약점 모두 검사
        severity: CRITICAL         # 심각도 높은 취약점만 보고 (선택 사항)  
        # (선택 사항) 취약점 보고서를 아티팩트로 저장하여 나중에 다운로드 가능하게 만들기
        output: trivy-report.txt